package com.example.vjcpyu;

import android.app.*; import android.content.*; import android.os.Build; import android.text.TextUtils;
import org.json.JSONArray; import org.json.JSONObject; import java.io.*; import java.net.*; import java.util.*;

public class PollReceiver extends BroadcastReceiver {
 private static final int REQ=1408;
 @Override public void onReceive(Context c,Intent i){if(!Config.prefs(c).getBoolean(Config.ENABLED,false))return; new Thread(()->poll(c,false)).start(); schedule(c);}
 static void createChannel(Context c){if(Build.VERSION.SDK_INT>=26){NotificationManager nm=(NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE); NotificationChannel ch=new NotificationChannel(Config.CHANNEL,"VJC → PXU Alerts",NotificationManager.IMPORTANCE_HIGH); ch.setDescription("Cảnh báo chuyến bay VJC từ HAN/SGN đến PXU"); nm.createNotificationChannel(ch);}}
 static void schedule(Context c){if(!Config.prefs(c).getBoolean(Config.ENABLED,false))return; AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE); PendingIntent pi=pending(c); long when=System.currentTimeMillis()+Config.POLL_MS; if(Build.VERSION.SDK_INT>=23)am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,when,pi);else am.set(AlarmManager.RTC_WAKEUP,when,pi);}
 static void cancel(Context c){((AlarmManager)c.getSystemService(Context.ALARM_SERVICE)).cancel(pending(c));}
 private static PendingIntent pending(Context c){Intent in=new Intent(c,PollReceiver.class);return PendingIntent.getBroadcast(c,REQ,in,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
 static String poll(Context c,boolean force){String token=Config.prefs(c).getString(Config.TOKEN,"");if(TextUtils.isEmpty(token))return "Chưa có FR24 API token.";HttpURLConnection x=null;try{String url=Config.BASE+"/live/flight-positions/full?airports=inbound:PXU&limit=100";x=(HttpURLConnection)new URL(url).openConnection();x.setRequestMethod("GET");x.setConnectTimeout(15000);x.setReadTimeout(20000);x.setRequestProperty("Authorization","Bearer "+token);x.setRequestProperty("Accept","application/json");x.setRequestProperty("Accept-Version","v1");int code=x.getResponseCode();String body=read(code>=200&&code<300?x.getInputStream():x.getErrorStream());if(code!=200)throw new IOException("HTTP "+code+(body.isEmpty()?"":": "+body));JSONArray data=new JSONObject(body).optJSONArray("data");if(data==null)data=new JSONArray();Set<String> old=parseIds(Config.prefs(c).getString(Config.LAST_IDS,""));Set<String> now=new HashSet<>();int matched=0,fresh=0;for(int i=0;i<data.length();i++){JSONObject f=data.optJSONObject(i);if(f==null)continue;String op=f.optString("operating_as","");String callsign=f.optString("callsign","");String flight=f.optString("flight","");String orig=f.optString("orig_iata","");String dest=f.optString("dest_iata","");boolean vjc="VJC".equalsIgnoreCase(op)||callsign.toUpperCase(Locale.US).startsWith("VJC")||flight.toUpperCase(Locale.US).startsWith("VJ");boolean route=("HAN".equalsIgnoreCase(orig)||"SGN".equalsIgnoreCase(orig))&&"PXU".equalsIgnoreCase(dest);if(!vjc||!route)continue;matched++;String id=f.optString("fr24_id",flight+"|"+orig+"|"+dest);now.add(id);if(!old.contains(id)){fresh++;notifyFlight(c,f);}}String status="Cập nhật "+new Date()+" — "+matched+" chuyến phù hợp; "+fresh+" chuyến mới.";Config.prefs(c).edit().putString(Config.LAST_IDS,TextUtils.join(",",now)).putString(Config.LAST_STATUS,status).putLong(Config.LAST_SUCCESS,System.currentTimeMillis()).apply();return status;}catch(Exception e){String msg="Lỗi kiểm tra: "+e.getMessage();Config.prefs(c).edit().putString(Config.LAST_STATUS,msg).apply();return msg;}finally{if(x!=null)x.disconnect();}}
 private static Set<String> parseIds(String s){Set<String> r=new HashSet<>();if(!TextUtils.isEmpty(s))for(String v:s.split(","))if(!v.trim().isEmpty())r.add(v.trim());return r;}
 static void notifyFlight(Context c,JSONObject f){createChannel(c);String flight=f.optString("flight",f.optString("callsign","VJC"));String callsign=f.optString("callsign","");String reg=f.optString("reg","");String type=f.optString("type","");String orig=f.optString("orig_iata","");String dest=f.optString("dest_iata","PXU");String eta=f.optString("eta","");String alt=f.has("alt")?String.valueOf(f.optInt("alt")):"";String detail=orig+" → "+dest+(reg.isEmpty()?"":" • "+reg)+(type.isEmpty()?"":" • "+type);if(!eta.isEmpty())detail+="\nETA: "+eta;if(!alt.isEmpty())detail+=" • "+alt+" ft";Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(c,Config.CHANNEL):new Notification.Builder(c);b.setSmallIcon(com.example.vjcpyu.R.drawable.ic_launcher).setContentTitle("Phát hiện VJC → PXU: "+flight).setContentText(detail.replace('\n',' ')).setStyle(new Notification.BigTextStyle().bigText(detail+(callsign.isEmpty()?"":"\nCallsign: "+callsign))).setAutoCancel(true).setCategory(Notification.CATEGORY_EVENT).setPriority(Notification.PRIORITY_HIGH);((NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE)).notify((int)(System.currentTimeMillis()%1000000),b.build());}
 static String read(InputStream in)throws Exception{if(in==null)return "";BufferedReader r=new BufferedReader(new InputStreamReader(in));StringBuilder s=new StringBuilder();String line;while((line=r.readLine())!=null)s.append(line);return s.toString();}
}
